on: [push]

jobs:
    stylua:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v3
            - name: Install Cargo
              run: curl https://sh.rustup.rs -sSf | sh
            - name: Install stylua
              run: cargo install stylua
            - name: stylua check
              run: stylua -c init.lua lua